"use client"

import { useState, useRef, useEffect } from "react"
import {
  ArrowLeft,
  Send,
  Download,
  Share2,
  Printer,
  MapPin,
  Shield,
  CloudSun,
  Thermometer,
  Droplets,
  QrCode,
  CheckCircle2,
  X,
  Loader2,
} from "lucide-react"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { useLanguage } from "@/lib/language-context"
import { useToastContext } from "@/lib/toast-context"
import { farmerProfile } from "@/lib/mock-data"
import type { DiseaseResult } from "@/lib/mock-data"

interface ReportScreenProps {
  result: DiseaseResult
  onBack: () => void
  onFileClaim?: () => void
}

export function ReportScreen(props: ReportScreenProps) {
  const result = props.result
  const onBack = props.onBack
  const { t } = useLanguage()
  const { showToast } = useToastContext()
  const [showSubmitModal, setShowSubmitModal] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [submitted, setSubmitted] = useState(false)
  const reportRef = useRef<HTMLDivElement>(null)

  const reportId = useRef(`KS-2024-${Math.random().toString(36).substr(2, 6).toUpperCase()}`).current
  const now = new Date()

  const expectedIncome = result.expectedYield * result.marketPrice
  const actualIncome = result.estimatedActualYield * result.marketPrice
  const estimatedLoss = expectedIncome - actualIncome
  const minClaim = Math.round(estimatedLoss * 0.8)

  const handleSubmitClaim = () => {
    setSubmitting(true)
    setTimeout(() => {
      setSubmitting(false)
      setSubmitted(true)
    }, 2000)
  }

  const handleDownloadPDF = () => {
    window.print()
    showToast("Print dialog opened for PDF download")
  }

  const handleWhatsApp = () => {
    const text = encodeURIComponent(
      `My KisanSaathi Crop Disease Claim Report ${reportId}\n\nDisease: ${result.name}\nSeverity: ${result.severity}\nEstimated Loss: \u20B9${estimatedLoss.toLocaleString("en-IN")}\n\nGenerated by KisanSaathi AI`
    )
    window.open(`https://wa.me/?text=${text}`, "_blank")
  }

  const handlePrint = () => {
    window.print()
  }

  return (
    <div className="flex flex-col gap-4">
      <button
        onClick={onBack}
        className="flex items-center gap-1 text-sm text-muted-foreground"
      >
        <ArrowLeft className="size-4" />
        {t("Back to results", "\u092A\u0930\u093F\u0923\u093E\u092E\u094B\u0902 \u092A\u0930 \u0935\u093E\u092A\u0938", "\u0C2B\u0C32\u0C3F\u0C24\u0C3E\u0C32\u0C15\u0C41 \u0C24\u0C3F\u0C30\u0C3F\u0C17\u0C3F")}
      </button>

      {/* Report Card */}
      <div ref={reportRef}>
        <Card className="overflow-hidden border-primary/20 print:border-0 print:shadow-none">
          <CardContent className="relative flex flex-col gap-5 p-5 md:p-8" style={{ fontFamily: "var(--font-libre), serif" }}>
            {/* Watermark */}
            <div className="pointer-events-none absolute inset-0 flex items-center justify-center opacity-[0.03]">
              <span className="text-[120px] font-bold text-foreground" style={{ transform: "rotate(-30deg)" }}>KisanSaathi</span>
            </div>

            {/* Report Header */}
            <div className="flex flex-col items-center gap-2 border-b border-border pb-4 text-center">
              <div className="flex items-center gap-2">
                <div className="flex size-8 items-center justify-center rounded-lg bg-primary">
                  <span className="text-sm font-bold text-primary-foreground">K</span>
                </div>
                <span className="text-lg font-bold text-foreground">KisanSaathi</span>
              </div>
              <h2 className="text-base font-bold text-foreground">
                {t("Official Crop Loss & Disease Report", "\u0906\u0927\u093F\u0915\u093E\u0930\u093F\u0915 \u092B\u0938\u0932 \u0939\u093E\u0928\u093F \u0914\u0930 \u0930\u094B\u0917 \u0930\u093F\u092A\u094B\u0930\u094D\u091F", "\u0C05\u0C27\u0C3F\u0C15\u0C3E\u0C30\u0C3F\u0C15 \u0C2A\u0C02\u0C1F \u0C28\u0C37\u0C4D\u0C1F\u0C02 & \u0C35\u0C4D\u0C2F\u0C3E\u0C27\u0C3F \u0C28\u0C3F\u0C35\u0C47\u0C26\u0C3F\u0C15")}
              </h2>
              <div className="flex flex-wrap items-center justify-center gap-3 text-xs text-muted-foreground">
                <span>{t("Report ID", "\u0930\u093F\u092A\u094B\u0930\u094D\u091F \u0906\u0908\u0921\u0940", "\u0C30\u0C3F\u0C2A\u0C4B\u0C30\u0C4D\u0C1F\u0C4D ID")}: {reportId}</span>
                <span>{now.toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}</span>
                <span>{now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}</span>
              </div>
              <div className="mt-1 flex size-14 items-center justify-center rounded-lg border border-border bg-muted">
                <QrCode className="size-8 text-muted-foreground" />
              </div>
            </div>

            {/* Section 1: Farmer Details */}
            <div>
              <h3 className="mb-2 text-sm font-bold uppercase tracking-wider text-primary">
                {t("1. Farmer Details", "1. \u0915\u093F\u0938\u093E\u0928 \u0935\u093F\u0935\u0930\u0923", "1. \u0C30\u0C48\u0C24\u0C41 \u0C35\u0C3F\u0C35\u0C30\u0C3E\u0C32\u0C41")}
              </h3>
              <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs">
                <div><span className="text-muted-foreground">Name:</span> <span className="font-medium text-foreground">{farmerProfile.name}</span></div>
                <div><span className="text-muted-foreground">Phone:</span> <span className="font-medium text-foreground">{farmerProfile.phone}</span></div>
                <div><span className="text-muted-foreground">Village:</span> <span className="font-medium text-foreground">{farmerProfile.village}</span></div>
                <div><span className="text-muted-foreground">District:</span> <span className="font-medium text-foreground">{farmerProfile.district}, {farmerProfile.state}</span></div>
                <div><span className="text-muted-foreground">Land Area:</span> <span className="font-medium text-foreground">{farmerProfile.landArea} acres</span></div>
                <div><span className="text-muted-foreground">GPS:</span> <span className="font-medium text-foreground">{`17.3850\u00b0 N, 78.4867\u00b0 E`}</span></div>
                <div className="col-span-2"><span className="text-muted-foreground">Policy No:</span> <span className="font-medium text-foreground">{farmerProfile.insurancePolicyNumber}</span></div>
              </div>
            </div>

            {/* Section 2: AI Disease Analysis */}
            <div>
              <h3 className="mb-2 text-sm font-bold uppercase tracking-wider text-primary">
                {t("2. AI Disease Analysis", "2. AI \u0930\u094B\u0917 \u0935\u093F\u0936\u094D\u0932\u0947\u0937\u0923", "2. AI \u0C35\u0C4D\u0C2F\u0C3E\u0C27\u0C3F \u0C35\u0C3F\u0C36\u0C4D\u0C32\u0C47\u0C37\u0C23")}
              </h3>
              <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs">
                <div><span className="text-muted-foreground">Disease:</span> <span className="font-semibold text-foreground">{result.name}</span></div>
                <div><span className="text-muted-foreground">Confidence:</span> <span className="font-semibold text-foreground">{result.confidence}%</span></div>
                <div><span className="text-muted-foreground">Severity:</span> <span className="font-semibold text-foreground">{result.severity}</span></div>
                <div><span className="text-muted-foreground">Crop Affected:</span> <span className="font-semibold text-foreground">{result.cropAffectedPct}%</span></div>
              </div>
              <div className="mt-2 flex items-center gap-2 rounded-lg bg-primary/10 px-3 py-2">
                <Shield className="size-4 text-primary" />
                <span className="text-xs font-medium text-primary">
                  {t("Verified by KisanSaathi AI Engine v2.1", "KisanSaathi AI \u0907\u0902\u091C\u0928 v2.1 \u0926\u094D\u0935\u093E\u0930\u093E \u0938\u0924\u094D\u092F\u093E\u092A\u093F\u0924", "KisanSaathi AI \u0C07\u0C02\u0C1C\u0C3F\u0C28\u0C4D v2.1 \u0C26\u0C4D\u0C35\u0C3E\u0C30\u0C3E \u0C27\u0C43\u0C35\u0C40\u0C15\u0C30\u0C3F\u0C02\u0C1A\u0C2C\u0C21\u0C3F\u0C02\u0C26\u0C3F")}
                </span>
              </div>
            </div>

            {/* Section 3: Weather Cross-Validation */}
            <div>
              <h3 className="mb-2 text-sm font-bold uppercase tracking-wider text-primary">
                {t("3. Weather Cross-Validation", "3. \u092E\u094C\u0938\u092E \u0915\u094D\u0930\u0949\u0938-\u0938\u0924\u094D\u092F\u093E\u092A\u0928", "3. \u0C35\u0C3E\u0C24\u0C3E\u0C35\u0C30\u0C23 \u0C15\u0C4D\u0C30\u0C3E\u0C38\u0C4D-\u0C27\u0C43\u0C35\u0C40\u0C15\u0C30\u0C23")}
              </h3>
              <div className="grid grid-cols-3 gap-2">
                <div className="flex flex-col items-center rounded-lg bg-muted p-2">
                  <Droplets className="size-4 text-accent-foreground" />
                  <span className="mt-1 text-sm font-bold text-foreground">87mm</span>
                  <span className="text-[10px] text-muted-foreground">Rainfall (3d)</span>
                </div>
                <div className="flex flex-col items-center rounded-lg bg-muted p-2">
                  <CloudSun className="size-4 text-secondary-foreground" />
                  <span className="mt-1 text-sm font-bold text-foreground">89%</span>
                  <span className="text-[10px] text-muted-foreground">Humidity</span>
                </div>
                <div className="flex flex-col items-center rounded-lg bg-muted p-2">
                  <Thermometer className="size-4 text-destructive" />
                  <span className="mt-1 text-sm font-bold text-foreground">{`28\u00b0C`}</span>
                  <span className="text-[10px] text-muted-foreground">Temperature</span>
                </div>
              </div>
              <div className="mt-2 flex items-center gap-2 rounded-lg bg-primary/10 px-3 py-2">
                <Shield className="size-4 text-primary" />
                <span className="text-xs font-medium text-primary">
                  {t("Weather conditions consistent with disease outbreak", "\u092E\u094C\u0938\u092E \u0915\u0940 \u0938\u094D\u0925\u093F\u0924\u093F \u0930\u094B\u0917 \u092A\u094D\u0930\u0915\u094B\u092A \u0915\u0947 \u0905\u0928\u0941\u0930\u0942\u092A", "\u0C35\u0C3E\u0C24\u0C3E\u0C35\u0C30\u0C23 \u0C2A\u0C30\u0C3F\u0C38\u0C4D\u0C25\u0C3F\u0C24\u0C41\u0C32\u0C41 \u0C35\u0C4D\u0C2F\u0C3E\u0C27\u0C3F \u0C35\u0C4D\u0C2F\u0C3E\u0C2A\u0C4D\u0C24\u0C3F\u0C15\u0C3F \u0C05\u0C28\u0C41\u0C17\u0C41\u0C23\u0C02\u0C17\u0C3E")}
                </span>
              </div>
              <p className="mt-1 text-[10px] text-muted-foreground">
                Source: India Meteorological Department + OpenWeatherMap
              </p>
            </div>

            {/* Section 4: Financial Loss */}
            <div>
              <h3 className="mb-2 text-sm font-bold uppercase tracking-wider text-primary">
                {t("4. Financial Loss Estimation", "4. \u0935\u093F\u0924\u094D\u0924\u0940\u092F \u0939\u093E\u0928\u093F \u0905\u0928\u0941\u092E\u093E\u0928", "4. \u0C06\u0C30\u0C4D\u0C25\u0C3F\u0C15 \u0C28\u0C37\u0C4D\u0C1F\u0C02 \u0C05\u0C02\u0C1A\u0C28\u0C3E")}
              </h3>
              <div className="grid grid-cols-2 gap-x-4 gap-y-2 text-xs">
                <div><span className="text-muted-foreground">Expected Yield:</span> <span className="font-medium text-foreground">{result.expectedYield} quintals</span></div>
                <div><span className="text-muted-foreground">Est. Actual Yield:</span> <span className="font-medium text-foreground">{result.estimatedActualYield} quintals</span></div>
                <div><span className="text-muted-foreground">Market Price:</span> <span className="font-medium text-foreground">{"\u20B9"}{result.marketPrice.toLocaleString("en-IN")}/quintal</span></div>
                <div><span className="text-muted-foreground">Expected Income:</span> <span className="font-medium text-foreground">{"\u20B9"}{expectedIncome.toLocaleString("en-IN")}</span></div>
                <div><span className="text-muted-foreground">Est. Actual Income:</span> <span className="font-medium text-foreground">{"\u20B9"}{actualIncome.toLocaleString("en-IN")}</span></div>
              </div>
              <div className="mt-3 rounded-xl border-2 border-destructive/30 bg-destructive/10 p-3 text-center">
                <p className="text-xs text-muted-foreground">{t("Estimated Loss", "\u0905\u0928\u0941\u092E\u093E\u0928\u093F\u0924 \u0939\u093E\u0928\u093F", "\u0C05\u0C02\u0C1A\u0C28\u0C3E \u0C28\u0C37\u0C4D\u0C1F\u0C02")}</p>
                <p className="text-2xl font-bold text-destructive">{"\u20B9"}{estimatedLoss.toLocaleString("en-IN")}</p>
              </div>
              <div className="mt-2 rounded-lg bg-muted p-2 text-center text-xs text-muted-foreground">
                {t("Recommended Claim Amount", "\u0905\u0928\u0941\u0936\u0902\u0938\u093F\u0924 \u0926\u093E\u0935\u093E \u0930\u093E\u0936\u093F", "\u0C38\u0C3F\u0C2B\u0C3E\u0C30\u0C4D\u0C38\u0C41 \u0C15\u0C4D\u0C32\u0C46\u0C2F\u0C3F\u0C2E\u0C4D \u0C2E\u0C4A\u0C24\u0C4D\u0C24\u0C02")}:{" "}
                <span className="font-bold text-foreground">{"\u20B9"}{minClaim.toLocaleString("en-IN")} {"\u2013"} {"\u20B9"}{estimatedLoss.toLocaleString("en-IN")}</span>
              </div>
            </div>

            {/* Section 5: Geo-tag */}
            <div>
              <h3 className="mb-2 text-sm font-bold uppercase tracking-wider text-primary">
                {t("5. Geo-tag & Location Proof", "5. \u091C\u093F\u092F\u094B-\u091F\u0948\u0917 \u0914\u0930 \u0938\u094D\u0925\u093E\u0928 \u092A\u094D\u0930\u092E\u093E\u0923", "5. \u0C1C\u0C3F\u0C2F\u0C4B-\u0C1F\u0C4D\u0C2F\u0C3E\u0C17\u0C4D & \u0C32\u0C4A\u0C15\u0C47\u0C37\u0C28\u0C4D \u0C2A\u0C4D\u0C30\u0C42\u0C2B\u0C4D")}
              </h3>
              <div className="flex items-center gap-3 rounded-lg bg-muted p-3">
                <MapPin className="size-5 text-primary" />
                <div className="text-xs">
                  <p className="font-medium text-foreground">{`17.3850\u00b0 N, 78.4867\u00b0 E`}</p>
                  <p className="text-muted-foreground">
                    {now.toLocaleString("en-IN")} | Device ID: ****a3f7
                  </p>
                </div>
              </div>
            </div>

            {/* Section 6: Declaration */}
            <div className="border-t border-border pt-4">
              <h3 className="mb-2 text-sm font-bold uppercase tracking-wider text-primary">
                {t("6. Declaration", "6. \u0918\u094B\u0937\u0923\u093E", "6. \u0C2A\u0C4D\u0C30\u0C15\u0C1F\u0C28")}
              </h3>
              <p className="text-xs leading-relaxed text-muted-foreground">
                {t(
                  "This report has been auto-generated by KisanSaathi AI system. All data has been cross-verified with satellite weather data and AI crop analysis. This report is valid for insurance claim submission.",
                  "\u092F\u0939 \u0930\u093F\u092A\u094B\u0930\u094D\u091F KisanSaathi AI \u092A\u094D\u0930\u0923\u093E\u0932\u0940 \u0926\u094D\u0935\u093E\u0930\u093E \u0938\u094D\u0935\u091A\u093E\u0932\u093F\u0924 \u0930\u0942\u092A \u0938\u0947 \u0924\u0948\u092F\u093E\u0930 \u0915\u0940 \u0917\u0908 \u0939\u0948\u0964",
                  "\u0C08 \u0C28\u0C3F\u0C35\u0C47\u0C26\u0C3F\u0C15 KisanSaathi AI \u0C35\u0C4D\u0C2F\u0C35\u0C38\u0C4D\u0C25 \u0C26\u0C4D\u0C35\u0C3E\u0C30\u0C3E \u0C38\u0C4D\u0C35\u0C2F\u0C02\u0C1A\u0C3E\u0C32\u0C15\u0C02\u0C17\u0C3E \u0C30\u0C42\u0C2A\u0C4A\u0C02\u0C26\u0C3F\u0C02\u0C1A\u0C2C\u0C21\u0C3F\u0C02\u0C26\u0C3F."
                )}
              </p>
              <div className="mt-3 flex items-center gap-2 border-t border-dashed border-border pt-3">
                <div className="h-8 w-32 rounded border border-muted-foreground/30 bg-muted/50" />
                <span className="text-[10px] text-muted-foreground">{t("Digital Signature", "\u0921\u093F\u091C\u093F\u091F\u0932 \u0939\u0938\u094D\u0924\u093E\u0915\u094D\u0937\u0930", "\u0C21\u0C3F\u0C1C\u0C3F\u0C1F\u0C32\u0C4D \u0C38\u0C02\u0C24\u0C15\u0C02")}</span>
              </div>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Action Buttons */}
      <div className="sticky bottom-20 grid grid-cols-2 gap-2 bg-background/95 py-3 backdrop-blur-sm print:hidden md:grid-cols-4">
        <Button
          size="lg"
          className="min-h-12 gap-2 bg-primary text-sm text-primary-foreground"
          onClick={() => setShowSubmitModal(true)}
        >
          <Send className="size-4" />
          {t("Submit Claim", "\u0926\u093E\u0935\u093E \u091C\u092E\u093E \u0915\u0930\u0947\u0902", "\u0C15\u0C4D\u0C32\u0C46\u0C2F\u0C3F\u0C2E\u0C4D \u0C38\u0C2E\u0C30\u0C4D\u0C2A\u0C3F\u0C02\u0C1A\u0C41")}
        </Button>
        <Button size="lg" variant="outline" className="min-h-12 gap-2 text-sm" onClick={handleDownloadPDF}>
          <Download className="size-4" />
          {t("PDF", "PDF", "PDF")}
        </Button>
        <Button size="lg" variant="outline" className="min-h-12 gap-2 text-sm" onClick={handleWhatsApp}>
          <Share2 className="size-4" />
          {t("WhatsApp", "WhatsApp", "WhatsApp")}
        </Button>
        <Button size="lg" variant="outline" className="min-h-12 gap-2 text-sm" onClick={handlePrint}>
          <Printer className="size-4" />
          {t("Print", "\u092A\u094D\u0930\u093F\u0902\u091F", "\u0C2A\u0C4D\u0C30\u0C3F\u0C02\u0C1F\u0C4D")}
        </Button>
      </div>

      {/* Submit Claim Modal */}
      {showSubmitModal && (
        <div
          className="fixed inset-0 z-[90] flex items-center justify-center bg-foreground/50 p-4 backdrop-blur-sm"
          onClick={(e) => { if (e.target === e.currentTarget && !submitting) setShowSubmitModal(false) }}
        >
          <div className="w-full max-w-sm animate-in zoom-in-95 rounded-2xl bg-card p-6 shadow-xl duration-200">
            {!submitted ? (
              <div className="flex flex-col items-center gap-4">
                <div className="flex size-16 items-center justify-center rounded-full bg-primary/15">
                  <Send className="size-7 text-primary" />
                </div>
                <h3 className="text-center font-serif text-lg font-bold text-foreground">
                  {t("Submit to Insurance Company?", "\u092C\u0940\u092E\u093E \u0915\u0902\u092A\u0928\u0940 \u0915\u094B \u091C\u092E\u093E \u0915\u0930\u0947\u0902?", "\u0C2C\u0C40\u0C2E\u0C3E \u0C15\u0C02\u0C2A\u0C46\u0C28\u0C40\u0C15\u0C3F \u0C38\u0C2E\u0C30\u0C4D\u0C2A\u0C3F\u0C02\u0C1A\u0C3E\u0C32\u0C3E?")}
                </h3>
                <p className="text-center text-sm text-muted-foreground">
                  {t(
                    `Report ${reportId} will be submitted to ${farmerProfile.insuranceCompany}`,
                    `\u0930\u093F\u092A\u094B\u0930\u094D\u091F ${reportId} ${farmerProfile.insuranceCompany} \u0915\u094B \u091C\u092E\u093E \u0915\u0940 \u091C\u093E\u090F\u0917\u0940`,
                    `\u0C28\u0C3F\u0C35\u0C47\u0C26\u0C3F\u0C15 ${reportId} ${farmerProfile.insuranceCompany}\u0C15\u0C3F \u0C38\u0C2E\u0C30\u0C4D\u0C2A\u0C3F\u0C02\u0C1A\u0C2C\u0C21\u0C41\u0C24\u0C41\u0C02\u0C26\u0C3F`
                  )}
                </p>
                <div className="flex w-full gap-2">
                  <Button
                    variant="outline"
                    className="flex-1"
                    onClick={() => setShowSubmitModal(false)}
                    disabled={submitting}
                  >
                    {t("Cancel", "\u0930\u0926\u094D\u0926 \u0915\u0930\u0947\u0902", "\u0C30\u0C26\u0C4D\u0C26\u0C41")}
                  </Button>
                  <Button
                    className="flex-1 bg-primary text-primary-foreground"
                    onClick={handleSubmitClaim}
                    disabled={submitting}
                  >
                    {submitting ? (
                      <><Loader2 className="mr-2 size-4 animate-spin" /> {t("Submitting...", "\u091C\u092E\u093E \u0939\u094B \u0930\u0939\u093E...", "\u0C38\u0C2E\u0C30\u0C4D\u0C2A\u0C3F\u0C38\u0C4D\u0C24\u0C4B\u0C02\u0C26\u0C3F...")}</>
                    ) : (
                      t("Confirm Submit", "\u091C\u092E\u093E \u0915\u0930\u0947\u0902", "\u0C38\u0C2E\u0C30\u0C4D\u0C2A\u0C3F\u0C02\u0C1A\u0C02\u0C21\u0C3F")
                    )}
                  </Button>
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center gap-4">
                <div className="flex size-16 items-center justify-center rounded-full bg-primary/15">
                  <CheckCircle2 className="size-8 text-primary" />
                </div>
                <h3 className="text-center font-serif text-lg font-bold text-primary">
                  {t("Claim Submitted Successfully!", "\u0926\u093E\u0935\u093E \u0938\u092B\u0932\u0924\u093E\u092A\u0942\u0930\u094D\u0935\u0915 \u091C\u092E\u093E!", "\u0C15\u0C4D\u0C32\u0C46\u0C2F\u0C3F\u0C2E\u0C4D \u0C35\u0C3F\u0C1C\u0C2F\u0C35\u0C02\u0C24\u0C02\u0C17\u0C3E \u0C38\u0C2E\u0C30\u0C4D\u0C2A\u0C3F\u0C02\u0C1A\u0C2C\u0C21\u0C3F\u0C02\u0C26\u0C3F!")}
                </h3>
                <div className="w-full rounded-lg bg-muted p-3 text-center">
                  <p className="text-xs text-muted-foreground">{t("Reference Number", "\u0938\u0902\u0926\u0930\u094D\u092D \u0938\u0902\u0916\u094D\u092F\u093E", "\u0C30\u0C3F\u0C2B\u0C30\u0C46\u0C28\u0C4D\u0C38\u0C4D \u0C28\u0C02\u0C2C\u0C30\u0C4D")}</p>
                  <p className="text-lg font-bold text-foreground">{reportId}</p>
                </div>
                <p className="text-center text-xs text-muted-foreground">
                  {t(
                    "You will receive SMS confirmation within 24 hours.",
                    "\u0906\u092A\u0915\u094B 24 \u0918\u0902\u091F\u0947 \u0915\u0947 \u092D\u0940\u0924\u0930 SMS \u092A\u0941\u0937\u094D\u091F\u093F \u092E\u093F\u0932\u0947\u0917\u0940\u0964",
                    "\u0C2E\u0C40\u0C15\u0C41 24 \u0C17\u0C02\u0C1F\u0C32\u0C4D\u0C32\u0C4B SMS \u0C28\u0C3F\u0C30\u0C4D\u0C27\u0C3E\u0C30\u0C23 \u0C05\u0C02\u0C26\u0C41\u0C24\u0C41\u0C02\u0C26\u0C3F."
                  )}
                </p>
                <Button
                  className="w-full bg-primary text-primary-foreground"
                  onClick={() => { setShowSubmitModal(false); setSubmitted(false) }}
                >
                  {t("Done", "\u0939\u094B \u0917\u092F\u093E", "\u0C2A\u0C42\u0C30\u0C4D\u0C24\u0C2F\u0C3F\u0C02\u0C26\u0C3F")}
                </Button>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
