export const farmerProfile = {
  name: "Ramesh Kumar",
  nameHindi: "रमेश कुमार",
  phone: "+91 98765 43210",
  aadhaar: "XXXX XXXX 4532",
  village: "Peddapalli",
  district: "Peddapalli",
  state: "Telangana",
  photo: "",
  cropType: "Rice",
  landArea: 5.2,
  insurancePolicyNumber: "PMFBY-TS-2025-78432",
  insuranceCompany: "Agriculture Insurance Co. of India",
  bankAccount: "XXXX XXXX XXXX 7891",
  verified: {
    aadhaar: true,
    landRecords: true,
  },
}

export const weatherData = {
  current: {
    temp: 32,
    humidity: 78,
    rainfall: 12,
    condition: "Partly Cloudy",
    windSpeed: 14,
  },
  weeklyRainfall: [
    { day: "Mon", value: 0 },
    { day: "Tue", value: 5 },
    { day: "Wed", value: 45 },
    { day: "Thu", value: 82 },
    { day: "Fri", value: 65 },
    { day: "Sat", value: 30 },
    { day: "Sun", value: 12 },
  ],
  weeklyTemp: [
    { day: "Mon", value: 34 },
    { day: "Tue", value: 33 },
    { day: "Wed", value: 29 },
    { day: "Thu", value: 26 },
    { day: "Fri", value: 28 },
    { day: "Sat", value: 31 },
    { day: "Sun", value: 32 },
  ],
}

export const alerts = [
  {
    id: 1,
    type: "flood",
    title: "Heavy Rainfall Alert",
    titleHindi: "भारी बारिश की चेतावनी",
    description: "Heavy rainfall expected in Peddapalli district for next 48 hours",
    time: "2 hours ago",
    severity: "high",
  },
  {
    id: 2,
    type: "pest",
    title: "Pest Warning",
    titleHindi: "कीट चेतावनी",
    description: "Brown planthopper outbreak reported in nearby villages",
    time: "5 hours ago",
    severity: "medium",
  },
  {
    id: 3,
    type: "drought",
    title: "Low Rainfall Advisory",
    titleHindi: "कम बारिश की सूचना",
    description: "Below-normal rainfall predicted for upcoming Kharif season",
    time: "1 day ago",
    severity: "low",
  },
]

export const equipmentListings = [
  {
    id: "eq1",
    name: "Mahindra 575 DI Tractor",
    type: "Tractor",
    owner: "Suresh Reddy",
    village: "Sultanabad",
    distance: 2.3,
    pricePerDay: 800,
    pricePerHour: 150,
    available: true,
    rating: 4.5,
    reviews: 23,
    image: "/tractor.jpg",
    model: "Mahindra 575 DI",
    year: 2021,
    capacity: "45 HP",
    fuelType: "Diesel",
    deliveryAvailable: true,
    deliveryCost: 200,
  },
  {
    id: "eq2",
    name: "Kubota DC-68G Harvester",
    type: "Harvester",
    owner: "Lakshmi Devi",
    village: "Ramagundam",
    distance: 4.7,
    pricePerDay: 2500,
    pricePerHour: 500,
    available: true,
    rating: 4.8,
    reviews: 15,
    image: "/harvester.jpg",
    model: "Kubota DC-68G",
    year: 2022,
    capacity: "68 HP",
    fuelType: "Diesel",
    deliveryAvailable: false,
    deliveryCost: 0,
  },
  {
    id: "eq3",
    name: "Seed Driller - Roto Seed",
    type: "Seed Driller",
    owner: "Venkat Rao",
    village: "Godavarikhani",
    distance: 1.5,
    pricePerDay: 400,
    pricePerHour: 80,
    available: false,
    rating: 4.2,
    reviews: 31,
    image: "/driller.jpg",
    model: "Roto Seed RSP-9",
    year: 2020,
    capacity: "9 Row",
    fuelType: "PTO Driven",
    deliveryAvailable: true,
    deliveryCost: 150,
  },
  {
    id: "eq4",
    name: "Honda WB30X Water Pump",
    type: "Water Pump",
    owner: "Anjali Kumari",
    village: "Peddapalli",
    distance: 0.8,
    pricePerDay: 200,
    pricePerHour: 50,
    available: true,
    rating: 4.6,
    reviews: 42,
    image: "/pump.jpg",
    model: "Honda WB30X",
    year: 2023,
    capacity: "3 inch",
    fuelType: "Petrol",
    deliveryAvailable: true,
    deliveryCost: 50,
  },
  {
    id: "eq5",
    name: "Rotavator - Shaktiman",
    type: "Rotavator",
    owner: "Srinivas Goud",
    village: "Manthani",
    distance: 3.1,
    pricePerDay: 600,
    pricePerHour: 120,
    available: true,
    rating: 4.3,
    reviews: 18,
    image: "/rotavator.jpg",
    model: "Shaktiman Regular",
    year: 2021,
    capacity: "5 ft",
    fuelType: "PTO Driven",
    deliveryAvailable: true,
    deliveryCost: 250,
  },
  {
    id: "eq6",
    name: "Battery Sprayer - Neptune",
    type: "Sprayer",
    owner: "Priya Devi",
    village: "Peddapalli",
    distance: 0.5,
    pricePerDay: 100,
    pricePerHour: 25,
    available: true,
    rating: 4.7,
    reviews: 56,
    image: "/sprayer.jpg",
    model: "Neptune BS-21",
    year: 2024,
    capacity: "16 Litre",
    fuelType: "Battery",
    deliveryAvailable: true,
    deliveryCost: 0,
  },
]

export const claims = [
  {
    id: "CLM-2025-001",
    crop: "Rice",
    lossAmount: 30000,
    damageType: "Flood",
    date: "2025-01-15",
    status: "approved",
    statusStep: 5,
    aiScore: 87,
    weatherVerified: true,
  },
  {
    id: "CLM-2025-002",
    crop: "Cotton",
    lossAmount: 45000,
    damageType: "Pest Attack",
    date: "2025-02-02",
    status: "under-review",
    statusStep: 3,
    aiScore: 74,
    weatherVerified: true,
  },
  {
    id: "CLM-2025-003",
    crop: "Wheat",
    lossAmount: 22000,
    damageType: "Storm",
    date: "2025-02-10",
    status: "submitted",
    statusStep: 1,
    aiScore: 91,
    weatherVerified: false,
  },
]

export const bookings = [
  {
    id: "BK-001",
    equipment: "Mahindra 575 DI Tractor",
    owner: "Suresh Reddy",
    date: "2025-02-20",
    duration: "Full Day",
    cost: 800,
    status: "upcoming",
  },
  {
    id: "BK-002",
    equipment: "Honda WB30X Water Pump",
    owner: "Anjali Kumari",
    date: "2025-02-14",
    duration: "4 Hours",
    cost: 200,
    status: "completed",
  },
  {
    id: "BK-003",
    equipment: "Battery Sprayer - Neptune",
    owner: "Priya Devi",
    date: "2025-02-01",
    duration: "Full Day",
    cost: 100,
    status: "completed",
  },
]

export const communityFeed = [
  {
    id: 1,
    type: "equipment",
    message: "New Tractor listed by Suresh Reddy in Sultanabad",
    time: "30 min ago",
  },
  {
    id: 2,
    type: "claim",
    message: "3 claims approved in your village this week",
    time: "2 hours ago",
  },
  {
    id: 3,
    type: "equipment",
    message: "Water Pump available at just Rs. 50/hour near you",
    time: "4 hours ago",
  },
]

export const transparencyStats = {
  claimsProcessed: 1247,
  avgClaimTime: 4.2,
  totalPayout: 23000000,
  farmersServed: 856,
}

export const claimStatuses = [
  "Submitted",
  "AI Verified",
  "Weather Checked",
  "Under Review",
  "Approved",
  "Paid",
]

export const damageTypes = [
  { id: "flood", label: "Flood", labelHindi: "बाढ़", icon: "Waves" },
  { id: "drought", label: "Drought", labelHindi: "सूखा", icon: "Sun" },
  { id: "pest", label: "Pest Attack", labelHindi: "कीट हमला", icon: "Bug" },
  { id: "storm", label: "Storm", labelHindi: "तूफ़ान", icon: "Wind" },
  { id: "fire", label: "Fire", labelHindi: "आग", icon: "Flame" },
  { id: "other", label: "Other", labelHindi: "अन्य", icon: "HelpCircle" },
]

export const cropTypes = [
  "Rice",
  "Wheat",
  "Cotton",
  "Sugarcane",
  "Maize",
  "Soybean",
  "Groundnut",
  "Others",
]

export const equipmentTypes = [
  "All",
  "Tractor",
  "Harvester",
  "Seed Driller",
  "Water Pump",
  "Rotavator",
  "Sprayer",
]

export const monthlyEarnings = [
  { month: "Sep", claims: 0, rental: 1200 },
  { month: "Oct", claims: 15000, rental: 2400 },
  { month: "Nov", claims: 0, rental: 800 },
  { month: "Dec", claims: 30000, rental: 1600 },
  { month: "Jan", claims: 45000, rental: 3200 },
  { month: "Feb", claims: 0, rental: 2000 },
]
